{
  "formatVersion": "1.1",
  "component": {
    "group": "org.apache.grails",
    "module": "grails-redis",
    "version": "5.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "redis.clients",
          "module": "jedis"
        },
        {
          "group": "com.google.code.gson",
          "module": "gson"
        }
      ],
      "files": [
        {
          "name": "grails-redis-5.0.0-SNAPSHOT.jar",
          "url": "grails-redis-5.0.0-SNAPSHOT.jar",
          "size": 138842,
          "sha512": "983c610b18b488a0fba0ccddda547391d5f7fef02c81623fa514742b093d98b3c88f785164be5f12057b1230c3e9b21a0bccc125bfbbad97a4b9852bb24fe35c",
          "sha256": "c2707b1e3530396fdf0bfd2dab5f6a6f489fe8fd7205e525fa7e6afb58696762",
          "sha1": "62ebe184bc39357bbfdea3c5c983419f6f358413",
          "md5": "c027776f7b98ec9e0510bdb65b1dde23"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.grails",
          "module": "grails-bom",
          "version": {
            "requires": "7.0.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "redis.clients",
          "module": "jedis"
        },
        {
          "group": "com.google.code.gson",
          "module": "gson"
        }
      ],
      "files": [
        {
          "name": "grails-redis-5.0.0-SNAPSHOT.jar",
          "url": "grails-redis-5.0.0-SNAPSHOT.jar",
          "size": 138842,
          "sha512": "983c610b18b488a0fba0ccddda547391d5f7fef02c81623fa514742b093d98b3c88f785164be5f12057b1230c3e9b21a0bccc125bfbbad97a4b9852bb24fe35c",
          "sha256": "c2707b1e3530396fdf0bfd2dab5f6a6f489fe8fd7205e525fa7e6afb58696762",
          "sha1": "62ebe184bc39357bbfdea3c5c983419f6f358413",
          "md5": "c027776f7b98ec9e0510bdb65b1dde23"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-redis-5.0.0-SNAPSHOT-javadoc.jar",
          "url": "grails-redis-5.0.0-SNAPSHOT-javadoc.jar",
          "size": 111510,
          "sha512": "2b7f23cd02a2231ccebe04ba48148b1d2f225b2805c80ba66f0197db1d76b4bcfd59128e5bb0320b5eaef9072a46d351164d1226e989a5fefd8b54fcf9095cf3",
          "sha256": "8f23b91e86bd092913c3dfc196a1e68c4e59b3e7d08d931ee9483d215214d62a",
          "sha1": "f81c2b2d5fd2ab570a43943da89de1a708ca2f09",
          "md5": "76afdfe75718d0ed93e200d320e80d96"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-redis-5.0.0-SNAPSHOT-sources.jar",
          "url": "grails-redis-5.0.0-SNAPSHOT-sources.jar",
          "size": 36981,
          "sha512": "d1bf4115843f6314d783ad5c1d6bc36b0fa75dc8c0a32ccca9f257f63acab40e2050fa7d7b1522c8b5133135e43bc5a587d710f9c07412d5809a5882db3c8f78",
          "sha256": "3ff797d169cf0929e0c693dc8ab78fb338081885fc4e430d369f3c96453c7a59",
          "sha1": "727ff9465e7c50873b0f7900ebf0236095d34383",
          "md5": "737007f71486595d34680ce19344e499"
        }
      ]
    }
  ]
}
