{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.mobilemind.api",
    "module": "gym-internal-api",
    "version": "3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.32"
          }
        }
      ],
      "files": [
        {
          "name": "gym-internal-api-3.0.1.jar",
          "url": "gym-internal-api-3.0.1.jar",
          "size": 23704,
          "sha512": "01ee601aff034418d099cf090970571ce6a55d0997392ef20414f676f4b47197a29bbe294c978a3bc8b52f265fba3ff0134e5235df8422bf5695bcfde6591222",
          "sha256": "1885d96d9fa8a0a4ee8d1264eab330fb80c8acb9ed83d11d7fd992f33760ea7b",
          "sha1": "e2d35a7ecf65bae73a3298d3d92d08a2b1cc87c0",
          "md5": "45d0bb302ba165838c5d596969ae1515"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.32"
          }
        }
      ],
      "files": [
        {
          "name": "gym-internal-api-3.0.1.jar",
          "url": "gym-internal-api-3.0.1.jar",
          "size": 23704,
          "sha512": "01ee601aff034418d099cf090970571ce6a55d0997392ef20414f676f4b47197a29bbe294c978a3bc8b52f265fba3ff0134e5235df8422bf5695bcfde6591222",
          "sha256": "1885d96d9fa8a0a4ee8d1264eab330fb80c8acb9ed83d11d7fd992f33760ea7b",
          "sha1": "e2d35a7ecf65bae73a3298d3d92d08a2b1cc87c0",
          "md5": "45d0bb302ba165838c5d596969ae1515"
        }
      ]
    }
  ]
}
