{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.flyway",
    "module": "flyway-core5",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "flyway-core5-1.0.jar",
          "url": "flyway-core5-1.0.jar",
          "size": 49847,
          "sha512": "db3fbb06f32d63ca4a2302d008a6beb987e99c11befc4021c29e7816d32342c67f69d9f316893e349f64aebbcaa9d4f82249d098ca000ccb33557c47962e8d08",
          "sha256": "d29bd14a385b571539aa7b2dcbb10dd129f8bd26e070ac4d7e8c4258ea76af3d",
          "sha1": "66ce7434488a9cdf4b4aec4f557e44f707f2074b",
          "md5": "c5282a705b18f99e0d577dd7fe2acc36"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.micronaut",
          "module": "micronaut-runtime"
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api"
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-jdbc"
        },
        {
          "group": "io.micronaut.sql",
          "module": "micronaut-jdbc-hikari"
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-core",
          "version": {
            "requires": "5.2.8-graalvm"
          }
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-inject"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-bom",
          "version": {
            "requires": "3.5.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "flyway-core5-1.0.jar",
          "url": "flyway-core5-1.0.jar",
          "size": 49847,
          "sha512": "db3fbb06f32d63ca4a2302d008a6beb987e99c11befc4021c29e7816d32342c67f69d9f316893e349f64aebbcaa9d4f82249d098ca000ccb33557c47962e8d08",
          "sha256": "d29bd14a385b571539aa7b2dcbb10dd129f8bd26e070ac4d7e8c4258ea76af3d",
          "sha1": "66ce7434488a9cdf4b4aec4f557e44f707f2074b",
          "md5": "c5282a705b18f99e0d577dd7fe2acc36"
        }
      ]
    }
  ]
}
