{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.flyway",
    "module": "flyway-core5",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "flyway-core5-1.0.jar",
          "url": "flyway-core5-1.0.jar",
          "size": 51733,
          "sha512": "f090a1cb302bc401f39bf6793cb8619c92146aea5e05dee7158968a93e13a1ed48348da7b9814ede3b360029447926b917b4c4b00c8c799cb6ed3817ce302566",
          "sha256": "12b09eade27edc686a393a07c927e90cb39f62303980115d8040cf4d2b3c59bd",
          "sha1": "a30b5f29f827906ddb6336c48adafbb18fa335a7",
          "md5": "e7dee6b03c68fe98e76787a999ed8833"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.micronaut",
          "module": "micronaut-runtime"
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api"
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-jdbc"
        },
        {
          "group": "io.micronaut.sql",
          "module": "micronaut-jdbc-hikari"
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-core",
          "version": {
            "requires": "5.2.8-graalvm"
          }
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-inject"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-bom",
          "version": {
            "requires": "3.5.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "flyway-core5-1.0.jar",
          "url": "flyway-core5-1.0.jar",
          "size": 51733,
          "sha512": "f090a1cb302bc401f39bf6793cb8619c92146aea5e05dee7158968a93e13a1ed48348da7b9814ede3b360029447926b917b4c4b00c8c799cb6ed3817ce302566",
          "sha256": "12b09eade27edc686a393a07c927e90cb39f62303980115d8040cf4d2b3c59bd",
          "sha1": "a30b5f29f827906ddb6336c48adafbb18fa335a7",
          "md5": "e7dee6b03c68fe98e76787a999ed8833"
        }
      ]
    }
  ]
}
