{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-plugin-services",
    "version": "6.2.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.37"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.21"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.3.37"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-core",
          "version": {
            "requires": "6.2.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-plugin-datasource",
          "version": {
            "requires": "6.2.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-plugin-services-6.2.1-SNAPSHOT.jar",
          "url": "grails-plugin-services-6.2.1-SNAPSHOT.jar",
          "size": 17696,
          "sha512": "b3c6850aea0a1b8ae5c3d572e547f4944255a38204bd281f6518d3da2ab716bcad2a3d9216df521950c3968d44d64f62ac92fcd3fe71236b832a43c5ba310aa5",
          "sha256": "b6f218c19d73065fe92d9cb9dfa7d502986bef851a64a26f62418a163d98e491",
          "sha1": "3af9eb1f7922e16a7a9b6b4727f8a26ce5ae1ec2",
          "md5": "960a66a2bdf5551a02450436318617bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.37"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.21"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.3.37"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-core",
          "version": {
            "requires": "6.2.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-plugin-datasource",
          "version": {
            "requires": "6.2.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-plugin-services-6.2.1-SNAPSHOT.jar",
          "url": "grails-plugin-services-6.2.1-SNAPSHOT.jar",
          "size": 17696,
          "sha512": "b3c6850aea0a1b8ae5c3d572e547f4944255a38204bd281f6518d3da2ab716bcad2a3d9216df521950c3968d44d64f62ac92fcd3fe71236b832a43c5ba310aa5",
          "sha256": "b6f218c19d73065fe92d9cb9dfa7d502986bef851a64a26f62418a163d98e491",
          "sha1": "3af9eb1f7922e16a7a9b6b4727f8a26ce5ae1ec2",
          "md5": "960a66a2bdf5551a02450436318617bf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-plugin-services-6.2.1-SNAPSHOT-javadoc.jar",
          "url": "grails-plugin-services-6.2.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "33e69927eb7fbd33e215876b7b6c2e8ca371f894fa6de404f98bd02dd28cb6023f0658dc0fac1dd2fee49cd616dc407f2b885de5cde172600c2e78e1095d3de0",
          "sha256": "d9a20aabf6ce23f27e5310de05e4e7fb4f698a75dc77e1173d2930828ed91969",
          "sha1": "2933bdd7eec7a36fc67286d997cd34ed4f2522aa",
          "md5": "c8eb3f0d3d0edb42d879a54216b11182"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-plugin-services-6.2.1-SNAPSHOT-sources.jar",
          "url": "grails-plugin-services-6.2.1-SNAPSHOT-sources.jar",
          "size": 4280,
          "sha512": "d6bf5a5259b63c8feccf15b5a39557f4565ab911652e8bf6d0e17f462d081bebd19faa0c47cc957bf570534aeba8001b813c6ca72a4c0f1df2124748c8888a94",
          "sha256": "961050b6bae27d2104cb40c8406393ad190315e6bf68f4888a3102f8adcde1ad",
          "sha1": "e615c75a866ce746554cec579c2086dcab8f5eac",
          "md5": "a801b46513750fa0272cec4fe4b462fd"
        }
      ]
    }
  ]
}
