{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-plugin-rest",
    "version": "7.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.servlet",
          "module": "jakarta.servlet-api",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.1.8"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.22"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web",
          "version": {
            "requires": "7.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-plugin-controllers",
          "version": {
            "requires": "7.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-plugin-datasource",
          "version": {
            "requires": "7.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails.plugins",
          "module": "converters",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-plugin-rest-7.0.0-SNAPSHOT.jar",
          "url": "grails-plugin-rest-7.0.0-SNAPSHOT.jar",
          "size": 218216,
          "sha512": "fba2cc116c8633e86ea978126978e1b0bc4cec9c4db691c0f7a5df75ca05c053654031872f96c254d72565be9c35870ce62d0286e3377ca22b48bbbc3327c770",
          "sha256": "726eaafcfd04cecbf87c372b6d451b8b0f605fe5f043db12d51085b0c9901b6a",
          "sha1": "37b160b6c86b246ad7cb1595f35463138e7b732e",
          "md5": "46321a850959ab793105f30cfc56e210"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine",
          "version": {
            "requires": "3.1.8"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "jakarta.servlet",
          "module": "jakarta.servlet-api",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.1.8"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.22"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web",
          "version": {
            "requires": "7.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-plugin-controllers",
          "version": {
            "requires": "7.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-plugin-datasource",
          "version": {
            "requires": "7.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails.plugins",
          "module": "converters",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-plugin-rest-7.0.0-SNAPSHOT.jar",
          "url": "grails-plugin-rest-7.0.0-SNAPSHOT.jar",
          "size": 218216,
          "sha512": "fba2cc116c8633e86ea978126978e1b0bc4cec9c4db691c0f7a5df75ca05c053654031872f96c254d72565be9c35870ce62d0286e3377ca22b48bbbc3327c770",
          "sha256": "726eaafcfd04cecbf87c372b6d451b8b0f605fe5f043db12d51085b0c9901b6a",
          "sha1": "37b160b6c86b246ad7cb1595f35463138e7b732e",
          "md5": "46321a850959ab793105f30cfc56e210"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-plugin-rest-7.0.0-SNAPSHOT-javadoc.jar",
          "url": "grails-plugin-rest-7.0.0-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "41bc69fa04db8b4dedf59ae98b37e34b50f55e63af8b37e3e93323ff0dfb8f9382daa14298ab41f400adcb69d6589700c3fd8eb4e6bdd80d412053104c182079",
          "sha256": "743afc9e16d02abddb79478072fcab77746d7219941e7e7f787ecae8ac463a9d",
          "sha1": "490f5582080f2d75621f790c169ee064c06d1808",
          "md5": "5d1a524c82b6786fddb464f5aaa4e2d0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-plugin-rest-7.0.0-SNAPSHOT-sources.jar",
          "url": "grails-plugin-rest-7.0.0-SNAPSHOT-sources.jar",
          "size": 57615,
          "sha512": "be17424b216f8b3d00bdbb269ba8b3d719afd1a6804b929b8fa78737a895e67a0b0f02f1870001dc51042e010987eb61c5679b9403a30a0f9ad0e99ba25c58b0",
          "sha256": "e9ec257e596ad6a89aa446c30397792f00cfdec3ae4fcd5cc7799e8a4717a721",
          "sha1": "9f0d320ebfc76ce5e821747539cf9ca711b01b6b",
          "md5": "dee1904f4c2e4fd57072f7cf1ab04920"
        }
      ]
    }
  ]
}
