{
  "formatVersion": "1.1",
  "component": {
    "group": "org.apache.grails",
    "module": "excel-export",
    "version": "3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "excel-export-3.0.jar",
          "url": "excel-export-3.0.jar",
          "size": 40849,
          "sha512": "649ffe8ac6984c9e25d687977f70b5b4ab072e0f0c4791c9d3de70825d3cee0e2361d47cd64866c8fa4b848e672b67753f69ed8f92b7189b092a9392acbd1182",
          "sha256": "80a1771b56bb21bf9f33172331b36122722a371f139eb5090ea6341aa6f064d0",
          "sha1": "96243642fd97063e7fd4624bfa5fc075528eb944",
          "md5": "4ab1bd1636d25e93f799a6bcfddbf3ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.grails",
          "module": "grails-bom",
          "version": {
            "requires": "7.0.0-RC2"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apache.grails",
          "module": "grails-cache",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-core",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-data-hibernate5",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-databinding",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-events",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-interceptors",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-logging",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-rest-transforms",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-services",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.poi",
          "module": "poi",
          "version": {
            "requires": "3.12"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "3.12"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            },
            {
              "group": "*",
              "module": "stax-api"
            }
          ]
        },
        {
          "group": "org.apache.poi",
          "module": "ooxml-schemas",
          "version": {
            "requires": "1.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            },
            {
              "group": "*",
              "module": "stax-api"
            }
          ]
        },
        {
          "group": "dom4j",
          "module": "dom4j",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "xml-apis",
          "module": "xml-apis",
          "version": {
            "requires": "1.4.01"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "excel-export-3.0.jar",
          "url": "excel-export-3.0.jar",
          "size": 40849,
          "sha512": "649ffe8ac6984c9e25d687977f70b5b4ab072e0f0c4791c9d3de70825d3cee0e2361d47cd64866c8fa4b848e672b67753f69ed8f92b7189b092a9392acbd1182",
          "sha256": "80a1771b56bb21bf9f33172331b36122722a371f139eb5090ea6341aa6f064d0",
          "sha1": "96243642fd97063e7fd4624bfa5fc075528eb944",
          "md5": "4ab1bd1636d25e93f799a6bcfddbf3ed"
        }
      ]
    }
  ]
}
