{
  "formatVersion": "1.1",
  "component": {
    "group": "org.apache.grails",
    "module": "grails-spring-security",
    "version": "7.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.grails.data",
          "module": "grails-datastore-core"
        },
        {
          "group": "org.apache.grails.data",
          "module": "grails-datamapping-core"
        },
        {
          "group": "org.apache.grails.events",
          "module": "grails-events-transforms"
        },
        {
          "group": "org.apache.grails",
          "module": "grails-mimetypes"
        },
        {
          "group": "org.apache.grails",
          "module": "grails-async"
        },
        {
          "group": "org.apache.grails.web",
          "module": "grails-web-common"
        },
        {
          "group": "org.apache.grails.web",
          "module": "grails-web-url-mappings"
        },
        {
          "group": "org.springframework",
          "module": "spring-beans"
        },
        {
          "group": "org.springframework",
          "module": "spring-context"
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-core"
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web"
        },
        {
          "group": "org.springframework",
          "module": "spring-web"
        }
      ],
      "files": [
        {
          "name": "grails-spring-security-7.0.0-SNAPSHOT.jar",
          "url": "grails-spring-security-7.0.0-SNAPSHOT.jar",
          "size": 580265,
          "sha512": "651008c2cb3e8bd3cfc504c701558c879fff8835cc572b9e3f69352c4af49f0101d2bad71aa58799f98de46a06481d41a68adbbf2c9781d84dd3489d76673ba1",
          "sha256": "37daf3276b6991852a220127283afddf100d142b2c68e973dd8422aab14dcf55",
          "sha1": "644e70b03657baa87480d3d701468c53ecb7714b",
          "md5": "8ae9e499e1c89c76605f9a9ebed3987f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.grails",
          "module": "grails-bom",
          "version": {
            "requires": "7.0.0-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text"
        },
        {
          "group": "org.ehcache",
          "module": "ehcache"
        },
        {
          "group": "org.apache.grails.bootstrap",
          "module": "grails-bootstrap"
        },
        {
          "group": "org.apache.grails",
          "module": "grails-rest-transforms"
        },
        {
          "group": "org.apache.grails",
          "module": "grails-converters"
        },
        {
          "group": "org.apache.grails",
          "module": "grails-events"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot"
        },
        {
          "group": "org.springframework",
          "module": "spring-context-support"
        },
        {
          "group": "org.springframework",
          "module": "spring-core"
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-crypto"
        },
        {
          "group": "org.springframework",
          "module": "spring-tx"
        },
        {
          "group": "org.apache.grails.data",
          "module": "grails-datastore-core"
        },
        {
          "group": "org.apache.grails.data",
          "module": "grails-datamapping-core"
        },
        {
          "group": "org.apache.grails.events",
          "module": "grails-events-transforms"
        },
        {
          "group": "org.apache.grails",
          "module": "grails-mimetypes"
        },
        {
          "group": "org.apache.grails",
          "module": "grails-async"
        },
        {
          "group": "org.apache.grails.web",
          "module": "grails-web-common"
        },
        {
          "group": "org.apache.grails.web",
          "module": "grails-web-url-mappings"
        },
        {
          "group": "org.springframework",
          "module": "spring-beans"
        },
        {
          "group": "org.springframework",
          "module": "spring-context"
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-core"
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web"
        },
        {
          "group": "org.springframework",
          "module": "spring-web"
        },
        {
          "group": "org.apache.grails",
          "module": "grails-services"
        }
      ],
      "files": [
        {
          "name": "grails-spring-security-7.0.0-SNAPSHOT.jar",
          "url": "grails-spring-security-7.0.0-SNAPSHOT.jar",
          "size": 580265,
          "sha512": "651008c2cb3e8bd3cfc504c701558c879fff8835cc572b9e3f69352c4af49f0101d2bad71aa58799f98de46a06481d41a68adbbf2c9781d84dd3489d76673ba1",
          "sha256": "37daf3276b6991852a220127283afddf100d142b2c68e973dd8422aab14dcf55",
          "sha1": "644e70b03657baa87480d3d701468c53ecb7714b",
          "md5": "8ae9e499e1c89c76605f9a9ebed3987f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-spring-security-7.0.0-SNAPSHOT-javadoc.jar",
          "url": "grails-spring-security-7.0.0-SNAPSHOT-javadoc.jar",
          "size": 403734,
          "sha512": "b20bbb8d879f9548d3d1dca8f98f72016d02c8c1ca59b96e6425186c30985ce389e1e22b7352800ac8a20945009e5f437355601e76180122b39a10ebe3095797",
          "sha256": "e2c87bdf0fb80755d8d661443a8eafe1cd56ff388e11955d88cd995696a980f6",
          "sha1": "2ad12496f3eb294db9b14124da706d5541af13ab",
          "md5": "c2f2b5206507eeb47edb6b312fad6384"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-spring-security-7.0.0-SNAPSHOT-sources.jar",
          "url": "grails-spring-security-7.0.0-SNAPSHOT-sources.jar",
          "size": 174858,
          "sha512": "087598d98d4e086d904fd552cc5959bcb3037a410c704e1c58d60fd3019f3eee2db3bff557b058d265f8b5435ab3b641f17e6c417660f5121f4d11f38efa8c9e",
          "sha256": "96e891875f93f49e22a72f7b547bf22abbbd70c73c9282cb92cacdc1eb9c40e0",
          "sha1": "30f17d0f76ccc7ab85d7b53c497dcc10c361ba12",
          "md5": "984617f69012e3486e88db4598a23d74"
        }
      ]
    }
  ]
}
