{
  "formatVersion": "1.1",
  "component": {
    "group": "io.groovy.swagger",
    "module": "groovy-swagger",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "groovy-swagger-0.0.1.jar",
          "url": "groovy-swagger-0.0.1.jar",
          "size": 75769,
          "sha512": "ca6e8803797a4b0962e79843dbe611d346bca10edf732d0a8cdbecf2ddadf1594438d3b61134f27e2d3ae485bb4cad0cd8ba5ab294cefc0ef93b565f5aa9fab7",
          "sha256": "e2a0a6fc5c44555ebc3abcf38801c96e1b47afd80fc112ab52f58794c1004b00",
          "sha1": "b091006262480d63c9cf9f262893c59d0d0da062",
          "md5": "fcbdccc21d965d28b67fc096bc8084ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.30"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-json",
          "version": {
            "requires": "4.0.30"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.5.0-jre"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "groovy-swagger-0.0.1.jar",
          "url": "groovy-swagger-0.0.1.jar",
          "size": 75769,
          "sha512": "ca6e8803797a4b0962e79843dbe611d346bca10edf732d0a8cdbecf2ddadf1594438d3b61134f27e2d3ae485bb4cad0cd8ba5ab294cefc0ef93b565f5aa9fab7",
          "sha256": "e2a0a6fc5c44555ebc3abcf38801c96e1b47afd80fc112ab52f58794c1004b00",
          "sha1": "b091006262480d63c9cf9f262893c59d0d0da062",
          "md5": "fcbdccc21d965d28b67fc096bc8084ce"
        }
      ]
    }
  ]
}
