{
  "formatVersion": "1.1",
  "component": {
    "group": "org.apache.grails",
    "module": "excel-export",
    "version": "7.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "excel-export-7.0.0.jar",
          "url": "excel-export-7.0.0.jar",
          "size": 40860,
          "sha512": "d9c1b29e3c9fcdcfc4b51442fb243a4a755fe97ad2551720b2343de7572f7602618b346bf47600cde71d1eff764e7cd7ac7764035c78abcafee48c98836cfcb6",
          "sha256": "1290a5495b289748906fd2922dad970d5ef0dcedc359208599cf409a0227ab60",
          "sha1": "1fdc8d4551d7f3c2ef0cbf17ec9bc5f15fad7fed",
          "md5": "9c607010a62a85c468426030e1b7c7d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.grails",
          "module": "grails-bom",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apache.grails",
          "module": "grails-cache",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-core",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-data-hibernate5",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-databinding",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-events",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-interceptors",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-logging",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-rest-transforms",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-services",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.poi",
          "module": "poi",
          "version": {
            "requires": "3.12"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "3.12"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            },
            {
              "group": "*",
              "module": "stax-api"
            }
          ]
        },
        {
          "group": "org.apache.poi",
          "module": "ooxml-schemas",
          "version": {
            "requires": "1.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            },
            {
              "group": "*",
              "module": "stax-api"
            }
          ]
        },
        {
          "group": "dom4j",
          "module": "dom4j",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "xml-apis",
          "module": "xml-apis",
          "version": {
            "requires": "1.4.01"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "excel-export-7.0.0.jar",
          "url": "excel-export-7.0.0.jar",
          "size": 40860,
          "sha512": "d9c1b29e3c9fcdcfc4b51442fb243a4a755fe97ad2551720b2343de7572f7602618b346bf47600cde71d1eff764e7cd7ac7764035c78abcafee48c98836cfcb6",
          "sha256": "1290a5495b289748906fd2922dad970d5ef0dcedc359208599cf409a0227ab60",
          "sha1": "1fdc8d4551d7f3c2ef0cbf17ec9bc5f15fad7fed",
          "md5": "9c607010a62a85c468426030e1b7c7d7"
        }
      ]
    }
  ]
}
