{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.mobilemind.api",
    "module": "gym-internal-api",
    "version": "2.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.23"
          }
        }
      ],
      "files": [
        {
          "name": "gym-internal-api-2.5.2.jar",
          "url": "gym-internal-api-2.5.2.jar",
          "size": 21625,
          "sha512": "3cdd1b9c509bcc7ce8213438c1ede049499f38453322dab126574382672398a2bb660561dea9260afea0edf99ccaec4bc005857708a7457c60f9ec14aecfe25a",
          "sha256": "46099bf11619e435d0221f57f4ad8de05cfaa9d1aee69d99058790109ffceab0",
          "sha1": "19490d1a960d5e3ff8d4255ed832f53499fbbee6",
          "md5": "05ebe85651df6024cc16c85dc9ad946e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.23"
          }
        }
      ],
      "files": [
        {
          "name": "gym-internal-api-2.5.2.jar",
          "url": "gym-internal-api-2.5.2.jar",
          "size": 21625,
          "sha512": "3cdd1b9c509bcc7ce8213438c1ede049499f38453322dab126574382672398a2bb660561dea9260afea0edf99ccaec4bc005857708a7457c60f9ec14aecfe25a",
          "sha256": "46099bf11619e435d0221f57f4ad8de05cfaa9d1aee69d99058790109ffceab0",
          "sha1": "19490d1a960d5e3ff8d4255ed832f53499fbbee6",
          "md5": "05ebe85651df6024cc16c85dc9ad946e"
        }
      ]
    }
  ]
}
