{
  "formatVersion": "1.1",
  "component": {
    "group": "org.codehaus.gant",
    "module": "gant",
    "version": "2.1.0-groovy5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gant-2.1.0-groovy5.jar",
          "url": "gant-2.1.0-groovy5.jar",
          "size": 245874,
          "sha512": "19151730326ea52cdcdd35bfb4a17f29711e61c2d898d7dd0ebdf667e8ab4328a1f0401ad8a2f0d3767e4650b26f188846f95cf479b09d3965000cea59028664",
          "sha256": "9c2460b70ec75bab0a44439498439146aad2c879fc406b28d178a1392cbc3a81",
          "sha1": "98b0259a7c5c1e7af207b4e07b8ee5b193f561c2",
          "md5": "627632b9869c515f83a2492ce63b06bb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "5.0.6"
          }
        },
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.17"
          }
        }
      ],
      "files": [
        {
          "name": "gant-2.1.0-groovy5.jar",
          "url": "gant-2.1.0-groovy5.jar",
          "size": 245874,
          "sha512": "19151730326ea52cdcdd35bfb4a17f29711e61c2d898d7dd0ebdf667e8ab4328a1f0401ad8a2f0d3767e4650b26f188846f95cf479b09d3965000cea59028664",
          "sha256": "9c2460b70ec75bab0a44439498439146aad2c879fc406b28d178a1392cbc3a81",
          "sha1": "98b0259a7c5c1e7af207b4e07b8ee5b193f561c2",
          "md5": "627632b9869c515f83a2492ce63b06bb"
        }
      ]
    }
  ]
}
