{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-shell",
    "version": "7.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.22"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-bootstrap",
          "version": {
            "requires": "7.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-gradle-model",
          "version": {
            "requires": "7.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-ant",
          "version": {
            "requires": "4.0.22"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-json",
          "version": {
            "requires": "4.0.22"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-jmx",
          "version": {
            "requires": "4.0.22"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "1.18"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "jline",
          "module": "jline",
          "version": {
            "requires": "2.14.6"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.gradle",
          "module": "gradle-tooling-api",
          "version": {
            "requires": "7.3-20210825160000+0000"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "4.0.22"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-cli",
          "version": {
            "requires": "3.2.6"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.codehaus.groovy",
              "module": "groovy"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-shell-7.0.0-SNAPSHOT.jar",
          "url": "grails-shell-7.0.0-SNAPSHOT.jar",
          "size": 669786,
          "sha512": "08248304c4e0429c0f79dfc4b991538532475c343b7a2e96a3364fbbe0a9cf7769b4c1818c7b93d259f98c0bbcb45a64d19ee224807d866d8d080c1f0f12d9c9",
          "sha256": "d14c39d6187c2ea8ebbc31adaafbbe263e5536c41e79d786f70cf40773d4f3aa",
          "sha1": "8e6240f3e9b6ea88100e5713d7f5f0940261e6db",
          "md5": "0900eed6d54230893bba7f729b3313db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-resolver-provider",
          "version": {
            "requires": "3.9.6"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "com.google.guava",
              "module": "guava"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-settings-builder",
          "version": {
            "requires": "3.6.3"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "javax.inject",
              "module": "javax.inject"
            }
          ]
        },
        {
          "group": "org.sonatype.plexus",
          "module": "plexus-sec-dispatcher",
          "version": {
            "requires": "1.4"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.sonatype.sisu",
          "module": "sisu-inject-plexus",
          "version": {
            "requires": "2.6.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "javax.enterprise",
              "module": "cdi-api"
            },
            {
              "group": "org.sonatype.sisu",
              "module": "sisu-inject-bean"
            }
          ]
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-connector-basic",
          "version": {
            "requires": "1.9.18"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-impl",
          "version": {
            "requires": "1.9.18"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-transport-file",
          "version": {
            "requires": "1.9.18"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-transport-http",
          "version": {
            "requires": "1.9.18"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "commons-codec",
              "module": "commons-codec"
            }
          ]
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.16.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.22"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-bootstrap",
          "version": {
            "requires": "7.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-gradle-model",
          "version": {
            "requires": "7.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-ant",
          "version": {
            "requires": "4.0.22"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-json",
          "version": {
            "requires": "4.0.22"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-jmx",
          "version": {
            "requires": "4.0.22"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "1.18"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "jline",
          "module": "jline",
          "version": {
            "requires": "2.14.6"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.gradle",
          "module": "gradle-tooling-api",
          "version": {
            "requires": "7.3-20210825160000+0000"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "4.0.22"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-cli",
          "version": {
            "requires": "3.2.6"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.codehaus.groovy",
              "module": "groovy"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-component-api",
          "version": {
            "requires": "1.0-alpha-33"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-shell-7.0.0-SNAPSHOT.jar",
          "url": "grails-shell-7.0.0-SNAPSHOT.jar",
          "size": 669786,
          "sha512": "08248304c4e0429c0f79dfc4b991538532475c343b7a2e96a3364fbbe0a9cf7769b4c1818c7b93d259f98c0bbcb45a64d19ee224807d866d8d080c1f0f12d9c9",
          "sha256": "d14c39d6187c2ea8ebbc31adaafbbe263e5536c41e79d786f70cf40773d4f3aa",
          "sha1": "8e6240f3e9b6ea88100e5713d7f5f0940261e6db",
          "md5": "0900eed6d54230893bba7f729b3313db"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-shell-7.0.0-SNAPSHOT-javadoc.jar",
          "url": "grails-shell-7.0.0-SNAPSHOT-javadoc.jar",
          "size": 437950,
          "sha512": "b76cc5b491656b6613c6c7d324c17d38d12f4d9e93d8106b45ed762799419b765d69e11f48c2c12e72f3ae360415df7ba49415dc7c157ab3990964b61527b68d",
          "sha256": "16dd49e0a8744a760c037be94c8b49e9102590d49085f707abf4b9e8199ed29a",
          "sha1": "f0487cbf64ac09e35d813b9a6bce00d1164190e2",
          "md5": "a3979adb0945382aa22609e8e22adcb2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-shell-7.0.0-SNAPSHOT-sources.jar",
          "url": "grails-shell-7.0.0-SNAPSHOT-sources.jar",
          "size": 256601,
          "sha512": "73400ed5b928df0edcde672d7b6c98160c692b9243b0a1e1037186f4d36ea489293f8d9d8d624812166a75874bf3dc6182577c096d72749b964122714690595b",
          "sha256": "8c5853e6d58978d60651bc61cb1f5906ea05995b42e9e35a05cc2203078ce144",
          "sha1": "e1636b011176ca9824f125aeb046b29aad044ae5",
          "md5": "7c93197d9025f9236edc29974053e9af"
        }
      ]
    }
  ]
}
