{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-plugin-rest",
    "version": "6.2.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.37"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.21"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web",
          "version": {
            "requires": "6.2.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-plugin-controllers",
          "version": {
            "requires": "6.2.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-plugin-datasource",
          "version": {
            "requires": "6.2.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails.plugins",
          "module": "converters",
          "version": {
            "requires": "5.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-plugin-rest-6.2.1-SNAPSHOT.jar",
          "url": "grails-plugin-rest-6.2.1-SNAPSHOT.jar",
          "size": 222915,
          "sha512": "767a55104f6ffbcc363af4ba5dd190ec4e633ecfcb9092644b0314c554f2b09e39903b3d6ebb1d38c2f64b2e02050a83b93880c2c1e4045e3a5f9577f5524f17",
          "sha256": "040f72f5831c4c53a0d4a4edea72b0bfb31f86cf6f2b00014cba720bc310d0c6",
          "sha1": "fdeedbeeefc339cae532231502e9820ced28df02",
          "md5": "a7779d943483c02a4ecdb64fe6be4bf2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine",
          "version": {
            "requires": "2.9.3"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.37"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.21"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web",
          "version": {
            "requires": "6.2.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-plugin-controllers",
          "version": {
            "requires": "6.2.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-plugin-datasource",
          "version": {
            "requires": "6.2.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails.plugins",
          "module": "converters",
          "version": {
            "requires": "5.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-plugin-rest-6.2.1-SNAPSHOT.jar",
          "url": "grails-plugin-rest-6.2.1-SNAPSHOT.jar",
          "size": 222915,
          "sha512": "767a55104f6ffbcc363af4ba5dd190ec4e633ecfcb9092644b0314c554f2b09e39903b3d6ebb1d38c2f64b2e02050a83b93880c2c1e4045e3a5f9577f5524f17",
          "sha256": "040f72f5831c4c53a0d4a4edea72b0bfb31f86cf6f2b00014cba720bc310d0c6",
          "sha1": "fdeedbeeefc339cae532231502e9820ced28df02",
          "md5": "a7779d943483c02a4ecdb64fe6be4bf2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-plugin-rest-6.2.1-SNAPSHOT-javadoc.jar",
          "url": "grails-plugin-rest-6.2.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "0335c0194ae63f7b599dcfd43e326fa52e836fc36615b67e27388841c3216db7ab8f35e02bc156008978cbf97adf3f8d3ed592f674a8734da085d531024653a8",
          "sha256": "3fbe79862f901630791633509169978a70cd2e6e25f2e9d130a6717d474ce4ad",
          "sha1": "ef47ace5f79057e7fbe1cd7e2e89fad915d51ea0",
          "md5": "2d131290ecda4ae5e48f8b08f4fd5b93"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-plugin-rest-6.2.1-SNAPSHOT-sources.jar",
          "url": "grails-plugin-rest-6.2.1-SNAPSHOT-sources.jar",
          "size": 57658,
          "sha512": "69de95418500b6f90d151466ccd8f8882ee2f9355ce122391d7d722cd8a402e3342df69bc6db4b53b20334b5bdb0e0070d5786f29d13dcf9114c5713dff998a9",
          "sha256": "d3f30770d296ccabd393647ead4e9f029fb4b60ae19247ee5144f022cbae53c6",
          "sha1": "4eb53e3db37e55db97c144cf372e1f0d7632f907",
          "md5": "6034b5bd4884c6b28d1812015eef9a06"
        }
      ]
    }
  ]
}
