{
  "formatVersion": "1.1",
  "component": {
    "group": "org.apache.grails",
    "module": "grails-reload",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "grails-reload-0.0.1.jar",
          "url": "grails-reload-0.0.1.jar",
          "size": 77475,
          "sha512": "ecaf9c7063d4d5e5015c7f822cef51182f10843dd46b77c30534f2848dba3d672496bbacdd5507e74f24cf76ee43c6b2eb9fad654b0fe7e322ea38812a6d2a6b",
          "sha256": "5ca7abbc70a9eee35993118b31ea54d5747dd420b7dc72ad191118c8ee52c6d5",
          "sha1": "5095b76983a94fd6713b3eb0ed0871274632f185",
          "md5": "e72843a5caa0c1a32c250c3bc0e83af8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.grails",
          "module": "grails-bom",
          "version": {
            "requires": "7.0.9"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apache.grails",
          "module": "grails-core",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-data-hibernate5",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-databinding",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-events",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-interceptors",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-logging",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-rest-transforms",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-services",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-url-mappings",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-web-boot",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.agent",
          "module": "reload-agent",
          "version": {
            "requires": "0.0.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-reload-0.0.1.jar",
          "url": "grails-reload-0.0.1.jar",
          "size": 77475,
          "sha512": "ecaf9c7063d4d5e5015c7f822cef51182f10843dd46b77c30534f2848dba3d672496bbacdd5507e74f24cf76ee43c6b2eb9fad654b0fe7e322ea38812a6d2a6b",
          "sha256": "5ca7abbc70a9eee35993118b31ea54d5747dd420b7dc72ad191118c8ee52c6d5",
          "sha1": "5095b76983a94fd6713b3eb0ed0871274632f185",
          "md5": "e72843a5caa0c1a32c250c3bc0e83af8"
        }
      ]
    }
  ]
}
