{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails.plugins",
    "module": "cache-ehcache",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.grails",
          "module": "grails-bom",
          "version": {
            "requires": "8.0.0-M6"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "cache-ehcache-6.0.0-SNAPSHOT.jar",
          "url": "cache-ehcache-6.0.0-SNAPSHOT.jar",
          "size": 19765,
          "sha512": "94836e58a37c4d4bb49c9e467510ddba2e87c71006433562310dd04d9ed6cead8abe7a6636cc0f513c60480a5b499c0dac800467ca1623b39f1796d7a4d44567",
          "sha256": "0e597b0afd6e5596817654cc2842f652b9ed067e73e25483b3ba45a9e7767e8a",
          "sha1": "7ce7773563d4cca6833079bf367cdd8d1160250f",
          "md5": "3f9d961148cd72464f5dd51992d9b61d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.grails",
          "module": "grails-bom",
          "version": {
            "requires": "8.0.0-M6"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apache.grails",
          "module": "grails-cache",
          "version": {
            "requires": "8.0.0-M6"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.ehcache",
          "module": "ehcache",
          "version": {
            "requires": "3.12.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.ehcache",
              "name": "ehcache-jakarta"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "cache-ehcache-6.0.0-SNAPSHOT.jar",
          "url": "cache-ehcache-6.0.0-SNAPSHOT.jar",
          "size": 19765,
          "sha512": "94836e58a37c4d4bb49c9e467510ddba2e87c71006433562310dd04d9ed6cead8abe7a6636cc0f513c60480a5b499c0dac800467ca1623b39f1796d7a4d44567",
          "sha256": "0e597b0afd6e5596817654cc2842f652b9ed067e73e25483b3ba45a9e7767e8a",
          "sha1": "7ce7773563d4cca6833079bf367cdd8d1160250f",
          "md5": "3f9d961148cd72464f5dd51992d9b61d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cache-ehcache-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "cache-ehcache-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 46244,
          "sha512": "2d85118f0a78d58603df71c3b8804a9b2a4457abe3084d94ad96f5088d8df6cf9decf47825bf12f84b5afc986f4e245ac0b62f54dd119e8342d6100c6ae77768",
          "sha256": "e6bffd4e5c10b78cf8595f529b9e2e003615b6baf1d3251e26334780c7c1c149",
          "sha1": "d82c6279cc5acde5d97d8f53089cbec72f1e32b6",
          "md5": "c9e5a9e0f075d15ef0d0cbcb3fc988c0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cache-ehcache-6.0.0-SNAPSHOT-sources.jar",
          "url": "cache-ehcache-6.0.0-SNAPSHOT-sources.jar",
          "size": 8959,
          "sha512": "9d220d364977b28c2bbffaa2ff542e3f1ec1ea6cf8eab570e5d5273960ebbe667afafe21299f594eff917125916b769752db8109f0943129d1ce581afd447c81",
          "sha256": "3377cb26963dcf90dcf99709b43795fa7c2cfc9cec1b00d1eea73a5e58a69fbc",
          "sha1": "f08ab33586073d9198eb92ccd4b5a93ef9e970d5",
          "md5": "aae0a656e9172f16a32e0237991b4c1e"
        }
      ]
    }
  ]
}
