{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-web",
    "version": "6.2.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.33"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.21"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-common",
          "version": {
            "requires": "6.2.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-databinding",
          "version": {
            "requires": "6.2.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-fileupload",
          "version": {
            "requires": "6.2.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-url-mappings",
          "version": {
            "requires": "6.2.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-mvc",
          "version": {
            "requires": "6.2.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-gsp",
          "version": {
            "requires": "6.2.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.grails",
              "module": "grails-encoder"
            },
            {
              "group": "org.grails",
              "module": "grails-core"
            },
            {
              "group": "org.grails",
              "module": "grails-web-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-web-6.2.1-SNAPSHOT.jar",
          "url": "grails-web-6.2.1-SNAPSHOT.jar",
          "size": 23602,
          "sha512": "bc0280b0970530bdacab9ce1bc7c39de770687f9258a699e1732ee20fb7f53add3ce2a3dee7753c88cb4ea2fccbc43040ca7f5f3d534a277e71ac535dd44ff21",
          "sha256": "b94982d97ae5f95d38b9bd783be6db01498adc997cae564a206e16b842403e26",
          "sha1": "b9586684000767d59604dbace62c8ef30e62ebe5",
          "md5": "8cc127987c465ee24985b90b5eb70b4a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.33"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.21"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-common",
          "version": {
            "requires": "6.2.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-databinding",
          "version": {
            "requires": "6.2.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-fileupload",
          "version": {
            "requires": "6.2.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-url-mappings",
          "version": {
            "requires": "6.2.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-mvc",
          "version": {
            "requires": "6.2.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-gsp",
          "version": {
            "requires": "6.2.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.grails",
              "module": "grails-encoder"
            },
            {
              "group": "org.grails",
              "module": "grails-core"
            },
            {
              "group": "org.grails",
              "module": "grails-web-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-web-6.2.1-SNAPSHOT.jar",
          "url": "grails-web-6.2.1-SNAPSHOT.jar",
          "size": 23602,
          "sha512": "bc0280b0970530bdacab9ce1bc7c39de770687f9258a699e1732ee20fb7f53add3ce2a3dee7753c88cb4ea2fccbc43040ca7f5f3d534a277e71ac535dd44ff21",
          "sha256": "b94982d97ae5f95d38b9bd783be6db01498adc997cae564a206e16b842403e26",
          "sha1": "b9586684000767d59604dbace62c8ef30e62ebe5",
          "md5": "8cc127987c465ee24985b90b5eb70b4a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-web-6.2.1-SNAPSHOT-javadoc.jar",
          "url": "grails-web-6.2.1-SNAPSHOT-javadoc.jar",
          "size": 125924,
          "sha512": "fe4bb13c649267a1a9955411671c6c2456ea4b11ea9cb9c6f0897b4a4e21d61ed8c85269c1a6419058d9db0cfa03498f1f6023d1e8cf812cbff51b0fffd9859b",
          "sha256": "7e86a25fad3ca6628a9e7eef8be3a196b0b2a3a8322778d6bab73f80c80d2651",
          "sha1": "d2039ddabedf429c82bfb7aee3edb30742f9e595",
          "md5": "c5aa77539f4829e0ef2aaac05a7719cf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-web-6.2.1-SNAPSHOT-sources.jar",
          "url": "grails-web-6.2.1-SNAPSHOT-sources.jar",
          "size": 16789,
          "sha512": "123e53e29d95e8d365f75962d049eb7886f7b2636e71a5fd2a0c57ca206b0503c94999511beda8921831c2dc8958b0ec1f725eda23ea4d153117fadecfc81ea1",
          "sha256": "591d7808b362a452261e31b2ffe65e30d1dfeb16a625246e72215ddc38543d0a",
          "sha1": "fdc60e513ffc2be096fc0fd4c8f055aaece8f42d",
          "md5": "0ec9d7aa1dabee9c816d3a47a8de8f7d"
        }
      ]
    }
  ]
}
