{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.flyway",
    "module": "flyway-core5-mysql5",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "flyway-core5-mysql5-1.0.jar",
          "url": "flyway-core5-mysql5-1.0.jar",
          "size": 52607,
          "sha512": "c0896cbfd7d033242ac0b44a23a6ea5833946fc9db6c679b1d59d0fb040d40bd51813cf3bef205a6a6b3f65879fa5a1e273814d8b4a9b8818ff0b872d03ecae2",
          "sha256": "e5d4c752f315cc271d9ad4bf1dd3531951574be6a5365cab5bbea9a31673f965",
          "sha1": "629d02ba88e2fa782c49b77f3d1634b3609c363c",
          "md5": "b02190919292c6a6f40394a224711fc9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.micronaut",
          "module": "micronaut-runtime"
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api"
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-jdbc"
        },
        {
          "group": "io.micronaut.sql",
          "module": "micronaut-jdbc-hikari"
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-core",
          "version": {
            "requires": "5.2.8-graalvm"
          }
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-inject"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-bom",
          "version": {
            "requires": "3.5.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "flyway-core5-mysql5-1.0.jar",
          "url": "flyway-core5-mysql5-1.0.jar",
          "size": 52607,
          "sha512": "c0896cbfd7d033242ac0b44a23a6ea5833946fc9db6c679b1d59d0fb040d40bd51813cf3bef205a6a6b3f65879fa5a1e273814d8b4a9b8818ff0b872d03ecae2",
          "sha256": "e5d4c752f315cc271d9ad4bf1dd3531951574be6a5365cab5bbea9a31673f965",
          "sha1": "629d02ba88e2fa782c49b77f3d1634b3609c363c",
          "md5": "b02190919292c6a6f40394a224711fc9"
        }
      ]
    }
  ]
}
