{
  "formatVersion": "1.1",
  "component": {
    "group": "org.apache.grails",
    "module": "grails-swagger",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "grails-swagger-0.0.1.jar",
          "url": "grails-swagger-0.0.1.jar",
          "size": 685966,
          "sha512": "ed9589e140b1b409dc1600b073c94f63fb9f17d2873aefa1b67631ddba84ea9a4a365cf198ea3ccf1d680b9a1e99dcd012922ac8632414c25f21d79a70f16c3c",
          "sha256": "c1d4c1fc79243f33119d9823185fb33dba1e25924e2b4778cb51e7c44306fdab",
          "sha1": "601abcd4c95637c04447bc450b1d100ddc7c59a9",
          "md5": "0ec22ccd5c93b874a007a66bdbe1075f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.grails",
          "module": "grails-bom",
          "version": {
            "requires": "7.0.7"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apache.grails",
          "module": "grails-core",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-data-hibernate5",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-databinding",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-events",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-gsp",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-interceptors",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-layout",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-logging",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-rest-transforms",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-scaffolding",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-services",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-url-mappings",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.apache.grails",
          "module": "grails-web-boot",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-undertow",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "io.groovy.swagger",
          "module": "groovy-swagger",
          "version": {
            "requires": "0.0.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "cloud.wondrify",
          "module": "asset-pipeline-grails",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-swagger-0.0.1.jar",
          "url": "grails-swagger-0.0.1.jar",
          "size": 685966,
          "sha512": "ed9589e140b1b409dc1600b073c94f63fb9f17d2873aefa1b67631ddba84ea9a4a365cf198ea3ccf1d680b9a1e99dcd012922ac8632414c25f21d79a70f16c3c",
          "sha256": "c1d4c1fc79243f33119d9823185fb33dba1e25924e2b4778cb51e7c44306fdab",
          "sha1": "601abcd4c95637c04447bc450b1d100ddc7c59a9",
          "md5": "0ec22ccd5c93b874a007a66bdbe1075f"
        }
      ]
    }
  ]
}
