{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-web-common",
    "version": "7.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.servlet",
          "module": "jakarta.servlet-api",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.1.8"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.22"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-core",
          "version": {
            "requires": "7.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.grails",
              "module": "grails-spring"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-databinding",
          "version": {
            "requires": "7.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-encoder",
          "version": {
            "requires": "7.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-gsp",
          "version": {
            "requires": "7.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.grails",
              "module": "grails-encoder"
            },
            {
              "group": "org.grails",
              "module": "grails-core"
            }
          ]
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-templates",
          "version": {
            "requires": "4.0.22"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "6.1.8"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-context-support",
          "version": {
            "requires": "6.1.8"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-web-common-7.0.0-SNAPSHOT.jar",
          "url": "grails-web-common-7.0.0-SNAPSHOT.jar",
          "size": 186911,
          "sha512": "ba4d29c12c21c8ac34c17837c20269f6f5d7d58953ca2a70cffa4795b2f558750fd52438b9b74fef460ec1159c88e832ffbcab163220683426d0a0eda554ca04",
          "sha256": "85657e9eb9f6fbd351c6033cc40a7c615b44ef0696fce43be62520551af2cc6b",
          "sha1": "4ec4c221d2863f8f84c83e2fb2babc9da46d7379",
          "md5": "58cd175adc651b22a448a86ad9946b87"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine",
          "version": {
            "requires": "3.1.8"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "jakarta.servlet",
          "module": "jakarta.servlet-api",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.1.8"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.22"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-core",
          "version": {
            "requires": "7.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.grails",
              "module": "grails-spring"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-databinding",
          "version": {
            "requires": "7.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-encoder",
          "version": {
            "requires": "7.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-gsp",
          "version": {
            "requires": "7.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.grails",
              "module": "grails-encoder"
            },
            {
              "group": "org.grails",
              "module": "grails-core"
            }
          ]
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-templates",
          "version": {
            "requires": "4.0.22"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "6.1.8"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-context-support",
          "version": {
            "requires": "6.1.8"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-web-common-7.0.0-SNAPSHOT.jar",
          "url": "grails-web-common-7.0.0-SNAPSHOT.jar",
          "size": 186911,
          "sha512": "ba4d29c12c21c8ac34c17837c20269f6f5d7d58953ca2a70cffa4795b2f558750fd52438b9b74fef460ec1159c88e832ffbcab163220683426d0a0eda554ca04",
          "sha256": "85657e9eb9f6fbd351c6033cc40a7c615b44ef0696fce43be62520551af2cc6b",
          "sha1": "4ec4c221d2863f8f84c83e2fb2babc9da46d7379",
          "md5": "58cd175adc651b22a448a86ad9946b87"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-web-common-7.0.0-SNAPSHOT-javadoc.jar",
          "url": "grails-web-common-7.0.0-SNAPSHOT-javadoc.jar",
          "size": 395769,
          "sha512": "b38493542e836b6f6eb7da78bb403b7aaac79d690bb6581e5c0be5682c3fe876d32707d13ba5d94db07139849a47a8f87e768007d76b2932f953f2b1805472a5",
          "sha256": "1d187f35e1883d6c4a4b3a6df410444f3cfce923cf36937cbd469eb92df4537c",
          "sha1": "43499228a69a6a1cf9ee88b0b199e9ea4117be00",
          "md5": "63ca89f6c278baa522c5f8589fec9541"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-web-common-7.0.0-SNAPSHOT-sources.jar",
          "url": "grails-web-common-7.0.0-SNAPSHOT-sources.jar",
          "size": 129441,
          "sha512": "0e4095e8c690f3e47e4b3844fdee8c96df0aad932f0c8e81786d6e3f380cd1b563b91414c6c312ffd0b5fb99db680553774b380d376ecfbf06e95d57c5b6a6c8",
          "sha256": "b67e39f3dab18a3e6e926bb18e9fd9b5bfc9f8d695fb4d0e6cdeb43051e52eba",
          "sha1": "b43d517f9b6ba765a5a42b0f1f3ede2972aa5ad9",
          "md5": "3f4d83af9bbd7d9c70d20c829c994d35"
        }
      ]
    }
  ]
}
