{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-core",
    "version": "7.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.22"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-inject",
          "version": {
            "requires": "4.6.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "io.micronaut.spring",
          "module": "micronaut-spring-context",
          "version": {
            "requires": "5.8.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "io.micronaut.cache",
          "module": "micronaut-cache-core",
          "version": {
            "requires": "5.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-runtime",
          "version": {
            "requires": "4.6.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "javax.persistence",
          "module": "javax.persistence-api",
          "version": {
            "requires": "2.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.6"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.8"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.1.8"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.8"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.8"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-bootstrap",
          "version": {
            "requires": "7.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.apache.ant",
              "module": "ant-junit"
            },
            {
              "group": "org.fusesource.jansi",
              "module": "jansi"
            },
            {
              "group": "org.apache.ivy",
              "module": "ivy"
            },
            {
              "group": "org.apache.ant",
              "module": "ant-trax"
            },
            {
              "group": "org.apache.ant",
              "module": "ant"
            },
            {
              "group": "net.java.dev.jna",
              "module": "jna"
            },
            {
              "group": "org.apache.groovy",
              "module": "groovy-ant"
            },
            {
              "group": "org.apache.ant",
              "module": "ant-launcher"
            },
            {
              "group": "org.codehaus.gant",
              "module": "gant_groovy1.8"
            },
            {
              "group": "jline",
              "module": "jline"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-spring",
          "version": {
            "requires": "7.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.springframework",
              "module": "spring-web"
            },
            {
              "group": "org.springframework",
              "module": "spring-tx"
            },
            {
              "group": "org.grails",
              "module": "grails-bootstrap"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-datastore-core",
          "version": {
            "requires": "8.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "jline",
          "module": "jline",
          "version": {
            "requires": "2.14.6"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "1.18"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-core-7.0.0-SNAPSHOT.jar",
          "url": "grails-core-7.0.0-SNAPSHOT.jar",
          "size": 766636,
          "sha512": "c36f648310f630f3f46d2df0ac8db805b64c802c17a0026d5f1e35aeea4742c2bb8867ee22dcbf7619a0dea1a0cc29da73dbfc06823ed4e12c33abf02296025e",
          "sha256": "a6a6a0e15c936e591b8b5059fba73bee648e2a3d1a16afe68788b05fd6920eb2",
          "sha1": "32a217788c38fa13d5c33e066d23f6b40b59ccf6",
          "md5": "104e92ef3d47ec402de88586aabc11f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine",
          "version": {
            "requires": "3.1.8"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.22"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-inject",
          "version": {
            "requires": "4.6.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "io.micronaut.spring",
          "module": "micronaut-spring-context",
          "version": {
            "requires": "5.8.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "io.micronaut.cache",
          "module": "micronaut-cache-core",
          "version": {
            "requires": "5.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-runtime",
          "version": {
            "requires": "4.6.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "javax.persistence",
          "module": "javax.persistence-api",
          "version": {
            "requires": "2.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.6"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.8"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.1.8"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.8"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.8"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-bootstrap",
          "version": {
            "requires": "7.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.apache.ant",
              "module": "ant-junit"
            },
            {
              "group": "org.fusesource.jansi",
              "module": "jansi"
            },
            {
              "group": "org.apache.ivy",
              "module": "ivy"
            },
            {
              "group": "org.apache.ant",
              "module": "ant-trax"
            },
            {
              "group": "org.apache.ant",
              "module": "ant"
            },
            {
              "group": "net.java.dev.jna",
              "module": "jna"
            },
            {
              "group": "org.apache.groovy",
              "module": "groovy-ant"
            },
            {
              "group": "org.apache.ant",
              "module": "ant-launcher"
            },
            {
              "group": "org.codehaus.gant",
              "module": "gant_groovy1.8"
            },
            {
              "group": "jline",
              "module": "jline"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-spring",
          "version": {
            "requires": "7.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.springframework",
              "module": "spring-web"
            },
            {
              "group": "org.springframework",
              "module": "spring-tx"
            },
            {
              "group": "org.grails",
              "module": "grails-bootstrap"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-datastore-core",
          "version": {
            "requires": "8.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "jline",
          "module": "jline",
          "version": {
            "requires": "2.14.6"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "1.18"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-core-7.0.0-SNAPSHOT.jar",
          "url": "grails-core-7.0.0-SNAPSHOT.jar",
          "size": 766636,
          "sha512": "c36f648310f630f3f46d2df0ac8db805b64c802c17a0026d5f1e35aeea4742c2bb8867ee22dcbf7619a0dea1a0cc29da73dbfc06823ed4e12c33abf02296025e",
          "sha256": "a6a6a0e15c936e591b8b5059fba73bee648e2a3d1a16afe68788b05fd6920eb2",
          "sha1": "32a217788c38fa13d5c33e066d23f6b40b59ccf6",
          "md5": "104e92ef3d47ec402de88586aabc11f1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-core-7.0.0-SNAPSHOT-javadoc.jar",
          "url": "grails-core-7.0.0-SNAPSHOT-javadoc.jar",
          "size": 915468,
          "sha512": "9d14c5de00e2bfbfe9edad02ae052feb517310317409b4859fa0eb6b3db849d8b8c8213621786bc4a1a41623a34f49128e19cd7a7740f8dfe13af99efc28bf87",
          "sha256": "54060e78252d08aa410816b1fdd14bea253ee51cb185dbd9238b0baa0c9c9547",
          "sha1": "e56fd8374209ba67e10aa89b4b473a715ceb1831",
          "md5": "4dbac90d4fbbbdc3b007d2df3a609824"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-core-7.0.0-SNAPSHOT-sources.jar",
          "url": "grails-core-7.0.0-SNAPSHOT-sources.jar",
          "size": 407775,
          "sha512": "924314b100adedb3582a3956279406efb85f2dc9f52b91c8cd708e54d2b172f6a4fdb5e21dac26bce8efb2e18c6d746b62a5b9a57a7dd84ac7fb12ce83cff17e",
          "sha256": "a3dfe4622a5bff4811179c4d18f8fc09a4d88bed3bf20adef1ee45e838f02dda",
          "sha1": "e6ac2967234d5e74aa9cb3026dfd8b9528aa29b6",
          "md5": "af7fc18246e878090a362b3d8b9de365"
        }
      ]
    }
  ]
}
